data:
  train_dataset: resources/external-f16-16384-128.csv
  val_dataset: resources/validation-sample-f16-16384-128.csv
  num_visual_tokens: 16384
  max_visual_length: 128
  max_text_length: 16

model:
  n_positions: 1024
  n_embd: 768
  n_layer: 12
  n_head: 12
  activation_function: gelu
  resid_pdrop: 0.1
  embd_pdrop: 0.1
  attn_pdrop: 0.1
  layer_norm_epsilon: 1e-5

optim:
  optimizer:
    lr: 2e-4
    betas: [0.9, 0.999]
    eps: 1e-6
    weight_decay: 0.01
  scheduler:
    name: linear
    num_warmup_steps: 10000
    num_training_steps: 2000000

train:
  batch_size: 256
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  gradient_checkpointing: false
  validation_interval: 0.25
  log_every_n_steps: 10